format = "$all"
add_newline = false
scan_timeout = 50
command_timeout = 500

[character]
success_symbol = "[âžœ](bold green) "
error_symbol = "[âžœ](bold red) "
vicmd_symbol = "[V](bold green) "

[directory]
truncation_length = 8

[git_status]
disabled  = false
format   = '([\($all_status$ahead_behind\)]($style) )'
ahead    = "â‡¡${count}"
behind   = "â‡£${count}"
diverged = "â‡•â‡¡${ahead_count} â‡£${behind_count}"
staged.enabled    = true
untracked.enabled = true
modified.enabled  = true

[lua]
format = "via [ðŸŒ• $version](bold blue) "

[package]
disabled = true

