
format = "$all"
add_newline = true
scan_timeout = 10

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"
[[battery.display]]
threshold = 10
style = "bold red"
[[battery.display]]
threshold = 30
style = "bold yellow"

[character]
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ](bold red) "
vicmd_symbol = "[V](bold green) "

[cmd_duration]
min_time = 1000
show_milliseconds = false
format = "took [$duration](bold yellow)"

[directory]
truncation_length = 8
# truncation_symbol = "â€¦/"

[git_status]
enabled = true
format = '([\($all_status$ahead_behind\)]($style) )'
ahead = "â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡•â‡¡${ahead_count} â‡£${behind_count}"
staged_count.enabled = true
untracked_count.enabled = true
modified_count.enabled = true

[hostname]
disabled = false
ssh_only = true
format =  "on [$hostname](bold red) "

[shell]
fish_indicator = "ïœ¹"
zsh_indicator = "ï‘ _"
disabled = false

